name: criterionscrape

# Controls when the action will run.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
    - uses: r-lib/actions/setup-r@main

    - name: Install packages
      run: |
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("readr")'
        R -e 'install.packages("rvest")'
        R -e 'install.packages("stringr")'
        R -e 'install.packages("usethis")'

    - name: Scrape
      run: |
         source("data-raw/criterion.R")
      shell: Rscript {0}


 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/*
        git commit -am "running scraper"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions

# resources
# https://blog--simonpcouch.netlify.app/blog/r-github-actions-commit/
# https://www.youtube.com/watch?v=N3NrWMxeeJQ&t=587s
